server:
  port: 88
spring:
  application:
    name: gateway-depl
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: auth-depl
          uri: lb://auth-depl
          predicates:
            - Path=/auth/**
          filters:
             - RewritePath=/auth(?<segment>/?.*), $\{segment}
        - id: shortener-depl
          uri: lb://shortener-depl
          predicates:
            - Path=/**
#          filters:
#            - RewritePath=/api(?<segment>/?.*), $\{segment}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka