apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortener-depl
  template:
    metadata:
      labels:
        app: shortener-depl
    spec:
      containers:
        - name: shortener-depl
          image: jiaqiwang118/url-shortener-service
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongouri
                  key: uri
            - name: URL_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: urlauthsecret
                  key: URL_AUTH_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: shortener-depl
  labels:
    app: shortener-depl
spec:
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app: shortener-depl