spring:
  application:
    name: schedule-depl
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: url-shortener
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/