name: Build and Deploy gateway service to GKE

on:
  push:
    branches:
      - main
    paths:
      - 'api-gateway/**'

env:
  PROJECT_ID: url-shortener-339504
  GKE_CLUSTER: url-shortener # Add your cluster name here.
  GKE_ZONE: us-central1-c # Add your cluster zone here.
  DEPLOYMENT_NAME: url-shortener # Add your deployment name here.
  IMAGE: static-site

jobs:
  deploy-gateway:
    name: Deploy gateway Service
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Jar
        run: cd api-gateway && mvn clean package

      - name: Init gcloud CLI
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: url-shortener-339504

      - name: Config Docker
        run: gcloud --quiet auth configure-docker

      - name: Build Docker Image
        run: |-
          cd api-gateway && docker build -t jiaqiwang118/url-gateway-service .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push jiaqiwang118/url-gateway-service

      - name: Deploy to GKE
        run: |-
          gcloud container clusters get-credentials url-shortener --zone=us-central1-c
          kubectl rollout restart deployment/gateway-depl
          kubectl get deployments -o wide